#!/usr/bin/env python
"""Regenerate a hash-pinned lock from a directory of downloaded wheels.

    python -m pip download --only-binary=:all: -d <dir> -r requirements.txt
    python tools/genlock.py <dir> > locks/<platform>-<abi>.txt

The lock is platform- and ABI-specific because at least one dependency ships
a compiled wheel (pydantic-core), so its hash only matches on the platform it
was downloaded for. build.py picks the lock matching the interpreter it is
bundling.
"""
import hashlib
import pathlib
import sys


def main(wheel_dir: str) -> int:
    wheels = sorted(pathlib.Path(wheel_dir).glob('*.whl'))
    if not wheels:
        print(f'no wheels in {wheel_dir}', file=sys.stderr)
        return 1
    print('# Generated by tools/genlock.py - do not edit by hand.')
    print('# Install with: pip install --require-hashes --only-binary=:all: -r <this file>')
    for w in wheels:
        parts = w.name.split('-')
        name, version = parts[0].replace('_', '-'), parts[1]
        digest = hashlib.sha256(w.read_bytes()).hexdigest()
        print(f'{name}=={version} --hash=sha256:{digest}')
    return 0


if __name__ == '__main__':
    sys.exit(main(sys.argv[1] if len(sys.argv) > 1 else 'wheels'))
